sonar.projectKey=proyecto-senia
sonar.projectName=proyecto-senia
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/api/**
sonar.javascript.lcov.reportPaths=coverage/lcov.docker.info
sonar.coverage.exclusions=src/openapi/**,src/scripts/**,src/loaders/**,src/index.js,src/app.js
